### ISSUE TITLE
How to construct the confusion network?

### ISSUE THREAD

**Issue by songkq** [DCGM/SoftCTC#1]
Hi, I'm trouble in how to construct the confusion network. Could you please give some kind advices?

**Comment by ikiss-fit** [comment]
Hi, in general, the confusion network represents the ground truth of a data sample. When training with regular CTC loss, the ground truth is in the form of a string, when training with the SoftCTC loss, the ground truth is in the form of a confusion network. A confusion network is a generalization of a string, where multiple possible characters can be at each position, each with a certain probability. In other words, a string is a confusion network where only one character can be at each position, with probability 1.

In the original [SoftCTC](https://arxiv.org/abs/2212.02135) paper, we use the confusion network as a ground truth representation for machine-annotated text lines in a semi-supervised scenario. To obtain the confusion network, we decode the output of the trained model using prefix decoding and then merge the hypotheses iteratively. Source codes for these steps can be found in the decoding part of our [pero-ocr](https://github.com/DCGM/pero-ocr) repository.

I hope I have answered your question and everything is clear now. If not, please let me know.

Please cite the appropriate papers if you use SoftCTC or pero-ocr in your research.
